on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ilammy/setup-nasm@v1
        with:
          version: 2.16.01
      - run: |
          git fetch --prune --unshallow
          nmake zip
      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: 'silicon.zip'
            
